export const steps = [
  {
    nodes: [
      { id: 1, state: "follower", term: 1 },
      { id: 2, state: "follower", term: 1 },
      { id: 3, state: "follower", term: 1 },
      { id: 4, state: "follower", term: 1 },
      { id: 5, state: "follower", term: 1 },
    ],
    messages: [],
    committed: [],
  },
  {
    nodes: [
      { id: 1, state: "candidate", term: 1 },
      { id: 2, state: "follower", term: 1 },
      { id: 3, state: "follower", term: 1 },
      { id: 4, state: "follower", term: 1 },
      { id: 5, state: "follower", term: 1 },
    ],
    messages: [
      { fromId: 1, toId: 2, type: "requestVote" },
      { fromId: 1, toId: 3, type: "requestVote" },
      { fromId: 1, toId: 4, type: "requestVote" },
      { fromId: 1, toId: 5, type: "requestVote" },
    ],
    committed: [],
  },
  {
    nodes: [
      { id: 1, state: "candidate", term: 1 },
      { id: 2, state: "follower", term: 1 },
      { id: 3, state: "follower", term: 1 },
      { id: 4, state: "follower", term: 1 },
      { id: 5, state: "follower", term: 1 },
    ],
    messages: [
      { fromId: 2, toId: 1, type: "voteGiven" },
      { fromId: 3, toId: 1, type: "voteGiven" },
      { fromId: 4, toId: 1, type: "voteGiven" },
      { fromId: 5, toId: 1, type: "voteGiven" },
    ],
    committed: [],
  },
  {
    nodes: [
      { id: 1, state: "leader", term: 1 },
      { id: 2, state: "follower", term: 1 },
      { id: 3, state: "follower", term: 1 },
      { id: 4, state: "follower", term: 1 },
      { id: 5, state: "follower", term: 1 },
    ],
    messages: [
      { fromId: 1, toId: 2, type: "appendEntries" },
      { fromId: 1, toId: 3, type: "appendEntries" },
      { fromId: 1, toId: 4, type: "appendEntries" },
      { fromId: 1, toId: 5, type: "appendEntries" },
    ],
    committed: [],
  },
  {
    nodes: [
      { id: 1, state: "leader", term: 1 },
      { id: 2, state: "follower", term: 1 },
      { id: 3, state: "follower", term: 1 },
      { id: 4, state: "follower", term: 1 },
      { id: 5, state: "follower", term: 1 },
    ],
    messages: [
      { fromId: 2, toId: 1, type: "reply" },
      { fromId: 3, toId: 1, type: "reply" },
      { fromId: 4, toId: 1, type: "reply" },
      { fromId: 5, toId: 1, type: "reply" },
    ],
    committed: [],
  },
  {
    nodes: [
      { id: 1, state: "leader", term: 1 },
      { id: 2, state: "follower", term: 1 },
      { id: 3, state: "follower", term: 1 },
      { id: 4, state: "follower", term: 1 },
      { id: 5, state: "follower", term: 1 },
    ],
    messages: [
      { fromId: 1, toId: 2, type: "appendEntries" },
      { fromId: 1, toId: 3, type: "appendEntries" },
      { fromId: 1, toId: 4, type: "appendEntries" },
      { fromId: 1, toId: 5, type: "appendEntries" },
    ],
    committed: [],
  },
  {
    nodes: [
      { id: 1, state: "leader", term: 1 },
      { id: 2, state: "follower", term: 1 },
      { id: 3, state: "follower", term: 1 },
      { id: 4, state: "follower", term: 1 },
      { id: 5, state: "follower", term: 1 },
    ],
    messages: [
      { fromId: 2, toId: 1, type: "reply" },
      { fromId: 3, toId: 1, type: "reply" },
      { fromId: 4, toId: 1, type: "reply" },
      { fromId: 5, toId: 1, type: "reply" },
    ],
    committed: [],
  },
  {
    nodes: [
      { id: 1, state: "leader", term: 1 },
      { id: 2, state: "follower", term: 1 },
      { id: 3, state: "follower", term: 1 },
      { id: 4, state: "follower", term: 1 },
      { id: 5, state: "follower", term: 1 },
    ],
    messages: [
      { fromId: 1, toId: 2, type: "appendEntries" },
      { fromId: 1, toId: 3, type: "appendEntries" },
      { fromId: 1, toId: 4, type: "appendEntries" },
      { fromId: 1, toId: 5, type: "appendEntries" },
    ],
    committed: [],
  },
  {
    nodes: [
      { id: 1, state: "leader", term: 1 },
      { id: 2, state: "follower", term: 1 },
      { id: 3, state: "follower", term: 1 },
      { id: 4, state: "follower", term: 1 },
      { id: 5, state: "follower", term: 1 },
    ],
    messages: [
      { fromId: 2, toId: 1, type: "reply" },
      { fromId: 3, toId: 1, type: "reply" },
      { fromId: 4, toId: 1, type: "reply" },
      { fromId: 5, toId: 1, type: "reply" },
    ],
    committed: [],
  },
  {
    nodes: [
      { id: 1, state: "leader", term: 1 },
      { id: 2, state: "follower", term: 1 },
      { id: 3, state: "follower", term: 1 },
      { id: 4, state: "follower", term: 1 },
      { id: 5, state: "follower", term: 1 },
    ],
    messages: [
      { fromId: 1, toId: 2, type: "appendEntries" },
      { fromId: 1, toId: 3, type: "appendEntries" },
      { fromId: 1, toId: 4, type: "appendEntries" },
      { fromId: 1, toId: 5, type: "appendEntries" },
    ],
    committed: [],
  },
  {
    nodes: [
      { id: 1, state: "leader", term: 1 },
      { id: 2, state: "follower", term: 1 },
      { id: 3, state: "follower", term: 1 },
      { id: 4, state: "follower", term: 1 },
      { id: 5, state: "follower", term: 1 },
    ],
    messages: [
      { fromId: 2, toId: 1, type: "reply" },
      { fromId: 3, toId: 1, type: "reply" },
      { fromId: 4, toId: 1, type: "reply" },
      { fromId: 5, toId: 1, type: "reply" },
    ],
    committed: [],
  },
  {
    nodes: [
      { id: 1, state: "leader", term: 1 },
      { id: 2, state: "follower", term: 1 },
      { id: 3, state: "follower", term: 1 },
      { id: 4, state: "follower", term: 1 },
      { id: 5, state: "follower", term: 1 },
    ],
    messages: [
      { fromId: 1, toId: 2, type: "appendEntries" },
      { fromId: 1, toId: 3, type: "appendEntries" },
      { fromId: 1, toId: 4, type: "appendEntries" },
      { fromId: 1, toId: 5, type: "appendEntries" },
    ],
    committed: [],
  },
  {
    nodes: [
      { id: 1, state: "leader", term: 1 },
      { id: 2, state: "follower", term: 1 },
      { id: 3, state: "follower", term: 1 },
      { id: 4, state: "follower", term: 1 },
      { id: 5, state: "follower", term: 1 },
    ],
    messages: [
      { fromId: 2, toId: 1, type: "reply" },
      { fromId: 3, toId: 1, type: "reply" },
      { fromId: 4, toId: 1, type: "reply" },
      { fromId: 5, toId: 1, type: "reply" },
    ],
    committed: [],
  },
  {
    nodes: [
      { id: 1, state: "leader", term: 1 },
      { id: 2, state: "follower", term: 1 },
      { id: 3, state: "follower", term: 1 },
      { id: 4, state: "follower", term: 1 },
      { id: 5, state: "follower", term: 1 },
    ],
    messages: [
      { fromId: 1, toId: 2, type: "appendEntries" },
      { fromId: 1, toId: 3, type: "appendEntries" },
      { fromId: 1, toId: 4, type: "appendEntries" },
      { fromId: 1, toId: 5, type: "appendEntries" },
    ],
    committed: [],
  },
  {
    nodes: [
      { id: 1, state: "leader", term: 1 },
      { id: 2, state: "follower", term: 1 },
      { id: 3, state: "follower", term: 1 },
      { id: 4, state: "follower", term: 1 },
      { id: 5, state: "follower", term: 1 },
    ],
    messages: [
      { fromId: 2, toId: 1, type: "reply" },
      { fromId: 3, toId: 1, type: "reply" },
      { fromId: 4, toId: 1, type: "reply" },
      { fromId: 5, toId: 1, type: "reply" },
    ],
    committed: [],
  },
  {
    nodes: [
      { id: 1, state: "leader", term: 1 },
      { id: 2, state: "follower", term: 1 },
      { id: 3, state: "follower", term: 1 },
      { id: 4, state: "follower", term: 1 },
      { id: 5, state: "follower", term: 1 },
    ],
    messages: [
      { fromId: 1, toId: 2, type: "appendEntries" },
      { fromId: 1, toId: 3, type: "appendEntries" },
      { fromId: 1, toId: 4, type: "appendEntries" },
      { fromId: 1, toId: 5, type: "appendEntries" },
    ],
    committed: [],
  },
  {
    nodes: [
      { id: 1, state: "leader", term: 1 },
      { id: 2, state: "follower", term: 1 },
      { id: 3, state: "follower", term: 1 },
      { id: 4, state: "follower", term: 1 },
      { id: 5, state: "follower", term: 1 },
    ],
    messages: [
      { fromId: 2, toId: 1, type: "reply" },
      { fromId: 3, toId: 1, type: "reply" },
      { fromId: 4, toId: 1, type: "reply" },
      { fromId: 5, toId: 1, type: "reply" },
    ],
    committed: [],
  },
  {
    nodes: [
      { id: 1, state: "leader", term: 1 },
      { id: 2, state: "follower", term: 1 },
      { id: 3, state: "follower", term: 1 },
      { id: 4, state: "follower", term: 1 },
      { id: 5, state: "follower", term: 1 },
    ],
    messages: [
      { fromId: 1, toId: 2, type: "appendEntries" },
      { fromId: 1, toId: 3, type: "appendEntries" },
      { fromId: 1, toId: 4, type: "appendEntries" },
      { fromId: 1, toId: 5, type: "appendEntries" },
    ],
    committed: [],
  },
  {
    nodes: [
      { id: 1, state: "leader", term: 1 },
      { id: 2, state: "follower", term: 1 },
      { id: 3, state: "follower", term: 1 },
      { id: 4, state: "follower", term: 1 },
      { id: 5, state: "follower", term: 1 },
    ],
    messages: [
      { fromId: 2, toId: 1, type: "reply" },
      { fromId: 3, toId: 1, type: "reply" },
      { fromId: 4, toId: 1, type: "reply" },
      { fromId: 5, toId: 1, type: "reply" },
    ],
    committed: [],
  },
  {
    nodes: [
      { id: 1, state: "leader", term: 1 },
      { id: 2, state: "follower", term: 1 },
      { id: 3, state: "follower", term: 1 },
      { id: 4, state: "follower", term: 1 },
      { id: 5, state: "follower", term: 1 },
    ],
    messages: [
      { fromId: 1, toId: 2, type: "appendEntries" },
      { fromId: 1, toId: 3, type: "appendEntries" },
      { fromId: 1, toId: 4, type: "appendEntries" },
      { fromId: 1, toId: 5, type: "appendEntries" },
    ],
    committed: [],
  },
  {
    nodes: [
      { id: 1, state: "leader", term: 1 },
      { id: 2, state: "follower", term: 1 },
      { id: 3, state: "follower", term: 1 },
      { id: 4, state: "follower", term: 1 },
      { id: 5, state: "follower", term: 1 },
    ],
    messages: [
      { fromId: 2, toId: 1, type: "reply" },
      { fromId: 3, toId: 1, type: "reply" },
      { fromId: 4, toId: 1, type: "reply" },
      { fromId: 5, toId: 1, type: "reply" },
    ],
    committed: [],
  },
];